### ISSUE TITLE
using the consul_acl module with https clusters

### ISSUE THREAD

**Issue by devops-rob** [mtchavez/consul-ansible-module#55]
I am trying to use the consul_acl module to create an ACL token for vault.  The consul cluster is using HTTPS.  The play looks like this:

```yaml
- name: create Vault ACL token
  consul_acl:
    host: "https://{{ item }}"
    mgmt_token: "{{ mgmt_token }}"
    port: "{{ https_port }}"
    scheme: https
    validate_certs: false
    state: present
    name: vault_token
    token_type: client
    rules:
      - node: ''
        policy: write
      - service: ''
        policy: read
  run_once: yes
  with_items:
    - "{{ consul_s1_ip }}"
    - "{{ consul_s2_ip }}"
    - "{{ consul_s3_ip }}"
    - "{{ consul_s4_ip }}"
    - "{{ consul_s5_ip }}"
```

i keep getting the following error message: 

```
msg": "Could not connect to consul agent at https://10.201.44.15:8501, error was HTTPSConnectionPool(host='<IP_ADDR>', port=8501): Max retries exceeded with url: /v1/acl/list?token=******** (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:579)'),))"
```
I can see no facility to add a cert and key to the API call happening underneath so how can i interact with my https cluster?
